package typescript

import (
	"bytes"
	"fmt"
	"strings"

	"ei-aitiger-codegraph/pkg/parser"
)

// Generated-source detection. A bundle, a compiled module or a file that
// says it is generated is output of sources already in the graph: it is
// declined with parser.ErrGeneratedSource, and the caller skips it.
const (
	generatedHeadBytes  = 4096  // where generation markers are written
	generatedTailBytes  = 1024  // where a source-map comment is written
	minifiedMinBytes    = 65536 // smaller files are never judged minified
	minifiedMeanLine    = 1000  // mean line length of minified output
	minifiedLongestLine = 50000 // a single line no hand-written file has
)

var generationMarkers = [][]byte{[]byte("@generated"), []byte("DO NOT EDIT"), []byte("Code generated by"), []byte("automatically generated"), []byte("This file is auto-generated")}

// generated reports why the content is generated output, or "" when it
// is not. A marker counts only on a comment line in the first 4 KiB, so a
// script that writes the marker into the files it generates is not itself
// declined; a source-map comment counts in the last KiB; a UMD wrapper in
// the first KiB; minification is judged on the mean line of a file of at
// least 8 KiB and the longest line of one of at least 64 KiB.
func generated(content []byte) string {
	head := content
	if len(head) > generatedHeadBytes {
		head = head[:generatedHeadBytes]
	}
	for _, line := range bytes.Split(head, []byte("\n")) {
		trimmed := bytes.TrimLeft(line, " \t")
		if !(bytes.HasPrefix(trimmed, []byte("//")) || bytes.HasPrefix(trimmed, []byte("/*")) || bytes.HasPrefix(trimmed, []byte("*")) || bytes.HasPrefix(trimmed, []byte("#"))) {
			continue
		}
		for _, marker := range generationMarkers {
			if bytes.Contains(trimmed, marker) {
				return "generated: marker " + string(marker)
			}
		}
	}
	if bytes.Contains(head, []byte("/* eslint-disable */")) && bytes.Contains(content, []byte("//# sourceMappingURL")) {
		return "generated: bundler header"
	}
	// A universal module definition wraps a library bundle: it exports to
	// CommonJS, AMD and a browser global alike.
	if start := head[:min(len(head), 1024)]; bytes.Contains(start, []byte("typeof exports")) && bytes.Contains(start, []byte("define.amd")) {
		return "generated: UMD bundle"
	}
	tail := content
	if len(tail) > generatedTailBytes {
		tail = tail[len(tail)-generatedTailBytes:]
	}
	if bytes.Contains(tail, []byte("//# sourceMappingURL=")) || bytes.Contains(tail, []byte("/*# sourceMappingURL=")) {
		return "generated: compiled output with a source map comment"
	}
	if len(content) >= shortMinifiedBytes {
		lines, longest, start := 0, 0, 0
		for {
			i := bytes.IndexByte(content[start:], '\n')
			if i < 0 {
				break
			}
			lines++
			if i > longest {
				longest = i
			}
			start += i + 1
		}
		if len(content)-start > longest {
			longest = len(content) - start
		}
		// From 8 KiB, lines of a thousand bytes on average are a
		// minifier's; from 64 KiB, so is one line of 50,000.
		if lines == 0 || len(content)/lines >= minifiedMeanLine || (len(content) >= minifiedMinBytes && longest >= minifiedLongestLine) {
			return fmt.Sprintf("minified: %d lines in %d bytes, longest %d", lines, len(content), longest)
		}
	}
	return ""
}

// minifiedNames are the file names minifiers write.
var minifiedNames = []string{".min.js", ".min.mjs", ".min.cjs", "-min.js", ".bundle.min.js", ".bundle.js", ".umd.js", ".umd.cjs", ".iife.js"}

// shortMinifiedBytes is the size from which a file of one or two lines is
// judged minified: no hand-written module is 8 KiB on one line.
const shortMinifiedBytes = 8192

// generatedFile is generated, judging the name as well: a minifier's file
// name, or a small file that is nearly all one line.
func generatedFile(path string, content []byte) string {
	for _, suffix := range minifiedNames {
		if strings.HasSuffix(path, suffix) {
			return "minified: named " + suffix
		}
	}
	if len(content) >= shortMinifiedBytes && len(content) < minifiedMinBytes && bytes.Count(content, []byte("\n")) <= 1 {
		return fmt.Sprintf("minified: %d bytes on one line", len(content))
	}
	return generated(content)
}

func errGenerated(reason string) error {
	return fmt.Errorf("%w: %s", parser.ErrGeneratedSource, reason)
}
