/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminPermissionsRouteImport } from './routes/admin/permissions'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as OrganizationsOrganizationIdRouteImport } from './routes/organizations/$organizationId'
import { Route as AdminOrganizationsIndexRouteImport } from './routes/admin/organizations/index'
import { Route as AdminOrganizationsOrganizationIdIndexRouteImport } from './routes/admin/organizations/$organizationId/index'
import { Route as OrganizationsOrganizationIdAgentsAgentIdRouteImport } from './routes/organizations/$organizationId_.agents.$agentId'
import { Route as OrganizationsOrganizationIdChatAgentsChatAgentIdRouteImport } from './routes/organizations/$organizationId_.chat-agents.$chatAgentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const OrganizationsOrganizationIdRoute =
  OrganizationsOrganizationIdRouteImport.update({
    id: '/organizations/$organizationId',
    path: '/organizations/$organizationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminOrganizationsIndexRoute = AdminOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrganizationsOrganizationIdIndexRoute =
  AdminOrganizationsOrganizationIdIndexRouteImport.update({
    id: '/organizations/$organizationId/',
    path: '/organizations/$organizationId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const OrganizationsOrganizationIdAgentsAgentIdRoute =
  OrganizationsOrganizationIdAgentsAgentIdRouteImport.update({
    id: '/organizations/$organizationId_/agents/$agentId',
    path: '/organizations/$organizationId/agents/$agentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizationsOrganizationIdChatAgentsChatAgentIdRoute =
  OrganizationsOrganizationIdChatAgentsChatAgentIdRouteImport.update({
    id: '/organizations/$organizationId_/chat-agents/$chatAgentId',
    path: '/organizations/$organizationId/chat-agents/$chatAgentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/settings': typeof SettingsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/organizations/$organizationId/agents/$agentId': typeof OrganizationsOrganizationIdAgentsAgentIdRoute
  '/organizations/$organizationId/chat-agents/$chatAgentId': typeof OrganizationsOrganizationIdChatAgentsChatAgentIdRoute
  '/admin/organizations/$organizationId/': typeof AdminOrganizationsOrganizationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/settings': typeof SettingsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/organizations': typeof AdminOrganizationsIndexRoute
  '/organizations/$organizationId/agents/$agentId': typeof OrganizationsOrganizationIdAgentsAgentIdRoute
  '/organizations/$organizationId/chat-agents/$chatAgentId': typeof OrganizationsOrganizationIdChatAgentsChatAgentIdRoute
  '/admin/organizations/$organizationId': typeof AdminOrganizationsOrganizationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/settings': typeof SettingsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/organizations/$organizationId': typeof OrganizationsOrganizationIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/organizations/': typeof AdminOrganizationsIndexRoute
  '/organizations/$organizationId_/agents/$agentId': typeof OrganizationsOrganizationIdAgentsAgentIdRoute
  '/organizations/$organizationId_/chat-agents/$chatAgentId': typeof OrganizationsOrganizationIdChatAgentsChatAgentIdRoute
  '/admin/organizations/$organizationId/': typeof AdminOrganizationsOrganizationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assistant'
    | '/settings'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/users'
    | '/organizations/$organizationId'
    | '/admin/'
    | '/admin/organizations/'
    | '/organizations/$organizationId/agents/$agentId'
    | '/organizations/$organizationId/chat-agents/$chatAgentId'
    | '/admin/organizations/$organizationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/settings'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/users'
    | '/organizations/$organizationId'
    | '/admin'
    | '/admin/organizations'
    | '/organizations/$organizationId/agents/$agentId'
    | '/organizations/$organizationId/chat-agents/$chatAgentId'
    | '/admin/organizations/$organizationId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assistant'
    | '/settings'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/users'
    | '/organizations/$organizationId'
    | '/admin/'
    | '/admin/organizations/'
    | '/organizations/$organizationId_/agents/$agentId'
    | '/organizations/$organizationId_/chat-agents/$chatAgentId'
    | '/admin/organizations/$organizationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AssistantRoute: typeof AssistantRoute
  SettingsRoute: typeof SettingsRoute
  OrganizationsOrganizationIdRoute: typeof OrganizationsOrganizationIdRoute
  OrganizationsOrganizationIdAgentsAgentIdRoute: typeof OrganizationsOrganizationIdAgentsAgentIdRoute
  OrganizationsOrganizationIdChatAgentsChatAgentIdRoute: typeof OrganizationsOrganizationIdChatAgentsChatAgentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/organizations/$organizationId': {
      id: '/organizations/$organizationId'
      path: '/organizations/$organizationId'
      fullPath: '/organizations/$organizationId'
      preLoaderRoute: typeof OrganizationsOrganizationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/organizations/': {
      id: '/admin/organizations/'
      path: '/organizations'
      fullPath: '/admin/organizations/'
      preLoaderRoute: typeof AdminOrganizationsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/organizations/$organizationId/': {
      id: '/admin/organizations/$organizationId/'
      path: '/organizations/$organizationId'
      fullPath: '/admin/organizations/$organizationId/'
      preLoaderRoute: typeof AdminOrganizationsOrganizationIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/organizations/$organizationId_/agents/$agentId': {
      id: '/organizations/$organizationId_/agents/$agentId'
      path: '/organizations/$organizationId/agents/$agentId'
      fullPath: '/organizations/$organizationId/agents/$agentId'
      preLoaderRoute: typeof OrganizationsOrganizationIdAgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$organizationId_/chat-agents/$chatAgentId': {
      id: '/organizations/$organizationId_/chat-agents/$chatAgentId'
      path: '/organizations/$organizationId/chat-agents/$chatAgentId'
      fullPath: '/organizations/$organizationId/chat-agents/$chatAgentId'
      preLoaderRoute: typeof OrganizationsOrganizationIdChatAgentsChatAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrganizationsIndexRoute: typeof AdminOrganizationsIndexRoute
  AdminOrganizationsOrganizationIdIndexRoute: typeof AdminOrganizationsOrganizationIdIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOrganizationsIndexRoute: AdminOrganizationsIndexRoute,
  AdminOrganizationsOrganizationIdIndexRoute:
    AdminOrganizationsOrganizationIdIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AssistantRoute: AssistantRoute,
  SettingsRoute: SettingsRoute,
  OrganizationsOrganizationIdRoute: OrganizationsOrganizationIdRoute,
  OrganizationsOrganizationIdAgentsAgentIdRoute:
    OrganizationsOrganizationIdAgentsAgentIdRoute,
  OrganizationsOrganizationIdChatAgentsChatAgentIdRoute:
    OrganizationsOrganizationIdChatAgentsChatAgentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
