package ingestion

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"ei-aitiger-codegraph/pkg/ir"
	"ei-aitiger-codegraph/worker/internal/discovery"
)

// A file past the source limit is generated output when its head or tail
// says so, and a gap in the graph otherwise.
func TestOversizedSourcesAreJudgedOnTheirEnds(t *testing.T) {
	bundle := []byte(strings.Repeat("var a=1,b=2,c=function(){return a+b};", 2000))
	for name, c := range map[string]struct{ head, tail string }{
		"minified":   {string(bundle), "x"},
		"source map": {"export const x = 1;\n", "\n//# sourceMappingURL=main.js.map\n"},
		"marker":     {"# Generated by the protocol buffer compiler.  DO NOT EDIT!\nimport x\n", "x\n"},
		"UMD":        {`(function(g,f){typeof exports=="object"?f(exports):typeof define=="function"&&define.amd?define(["exports"],f):f(g.x={})})(this,function(e){` + "\n", "});\n"},
	} {
		if oversizedGenerated([]byte(c.head), []byte(c.tail)) == "" {
			t.Fatalf("%s: not judged generated", name)
		}
	}
	code := []byte(strings.Repeat("public void handle(Request request) {\n    service.handle(request);\n}\n", 900))
	if why := oversizedGenerated(code, code[len(code)-1024:]); why != "" {
		t.Fatalf("hand-written code judged generated: %s", why)
	}
}

func TestSniffSourceReadsOnlyTheEnds(t *testing.T) {
	dir := t.TempDir()
	body := strings.Repeat("a", 100_000) + "TAIL"
	if err := os.WriteFile(filepath.Join(dir, "big.js"), []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}
	root, err := os.OpenRoot(dir)
	if err != nil {
		t.Fatal(err)
	}
	defer root.Close()
	head, tail, err := discovery.SniffSource(context.Background(), root, ir.Source{Path: "big.js"}, 1024, 4)
	if err != nil || len(head) != 1024 || string(tail) != "TAIL" {
		t.Fatalf("sniff: %d %q %v", len(head), tail, err)
	}
}
