// Copies the @forge-ui components a standalone agent's UI is made of into the
// agent runtime package (forge_agent_runtime/starter/web_vendor), which writes
// them into every project it generates: the theme (index-css), the floating
// assistant (assistant) and everything they need, resolved from the built
// registry (public/r) as `shadcn add` would. A generated project then installs
// with a plain `npm install`, without the registry's token.
//
//   npm run starter:build            # after npm run registry:build
//   npm run starter:build -- --check # fails when the copy is out of date
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const registry = path.join(root, "public/r")
const target = path.resolve(
  root,
  "../python/agent-runtime/src/forge_agent_runtime/starter/web_vendor"
)
// What a standalone agent's UI installs; `base` only for its own files (src/lib/utils.ts).
const ROOTS = ["index-css", "assistant"]
const OWN_FILES_ONLY = ["base"]

// Where an item's file goes in the project, as components.json's aliases put it.
const ALIASES = {
  "@components/": "src/components/",
  "@ui/": "src/components/ui/",
  "@lib/": "src/lib/",
  "@hooks/": "src/hooks/",
}

const item = async (name) =>
  JSON.parse(await readFile(path.join(registry, `${name}.json`), "utf8"))

const ownPackage = JSON.parse(await readFile(path.join(root, "package.json"), "utf8"))
const versionOf = (spec) => {
  // "@scope/name@^1.2" or "name@^1" or a bare name (the demo app's version).
  const at = spec.lastIndexOf("@")
  if (at > 0) return [spec.slice(0, at), spec.slice(at + 1)]
  return [spec, ownPackage.dependencies?.[spec] ?? ownPackage.devDependencies?.[spec] ?? "latest"]
}

const files = new Map()
const dependencies = {}
const seen = new Set()
const visit = async (name, ownOnly = false) => {
  if (seen.has(name)) return
  seen.add(name)
  const entry = await item(name)
  for (const file of entry.files ?? []) {
    const where = file.target ?? file.path
    const prefix = Object.keys(ALIASES).find((p) => where.startsWith(p))
    files.set(prefix ? ALIASES[prefix] + where.slice(prefix.length) : where, file.content)
  }
  for (const spec of entry.dependencies ?? []) {
    const [pkg, version] = versionOf(spec)
    dependencies[pkg] = version
  }
  if (ownOnly) return
  for (const dep of entry.registryDependencies ?? []) {
    await visit(dep.replace(/^@forge-ui\//, ""))
  }
}
for (const name of ROOTS) await visit(name)
for (const name of OWN_FILES_ONLY) await visit(name, true)
const base = await item("base")

const manifest = {
  about:
    "Generated by packages/forge-ui/scripts/build-starter.mjs from the @forge-ui registry; don't edit by hand.",
  items: [...seen].sort(),
  dependencies: Object.fromEntries(Object.entries(dependencies).sort()),
  components: base.config,
}
const wanted = new Map([
  ...[...files].map(([file, content]) => [file, content]),
  ["manifest.json", `${JSON.stringify(manifest, null, 2)}\n`],
])

const existing = async (dir, prefix = "") => {
  const out = new Map()
  let entries
  try {
    entries = await readdir(dir, { withFileTypes: true })
  } catch {
    return out
  }
  for (const entry of entries) {
    const rel = path.posix.join(prefix, entry.name)
    if (entry.isDirectory()) {
      for (const [k, v] of await existing(path.join(dir, entry.name), rel)) out.set(k, v)
    } else {
      out.set(rel, await readFile(path.join(dir, entry.name), "utf8"))
    }
  }
  return out
}

const shown = path.relative(process.cwd(), target)
if (process.argv.includes("--check")) {
  const now = await existing(target)
  const stale = [
    ...[...wanted].filter(([file, content]) => now.get(file) !== content).map(([f]) => f),
    ...[...now.keys()].filter((file) => !wanted.has(file)),
  ]
  if (stale.length) {
    console.error(`${shown} is out of date (${stale.slice(0, 5).join(", ")}…): run npm run starter:build`)
    process.exit(1)
  }
  console.log(`The standalone agent's UI (${files.size} files) is up to date.`)
} else {
  await rm(target, { recursive: true, force: true })
  for (const [file, content] of wanted) {
    const to = path.join(target, file)
    await mkdir(path.dirname(to), { recursive: true })
    await writeFile(to, content)
  }
  console.log(`Wrote ${files.size} files from ${seen.size} items to ${shown}`)
}
